### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/csqa/inhouse_split_qids.txt'

### ISSUE THREAD

**Issue by dxlong2000** [snap-stanford/GreaseLM#5]
Hi Xikun,

Thanks for your great work. May I ask where could I take this ```inhouse_split_qids.txt``` file?

```
***** hyperparameters *****
dataset: csqa
******************************
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
ModelClass <class 'transformers.modeling_roberta.RobertaModel'>
NLP
pid: 493
screen: 

gpu: 1

torch version: 1.8.0+cu101
torch cuda version: 10.1
cuda is available: True
cuda device count: 1
cudnn version: 7603
wandb id:  1iygcifx
loading from checkpoint: ./checkpoints/csqa/csqa_model.pt
train_statement_path ./data//csqa/statement/train.statement.jsonl
num_choice 5
Loading sparse adj data...
| ori_adj_len: mu 12.13 sigma 9.67 | adj_len: 13.13 | prune_rate： 0.00 | qc_num: 5.46 | ac_num: 1.54 |
Finish loading training data.
Loading sparse adj data...
| ori_adj_len: mu 12.16 sigma 10.18 | adj_len: 13.16 | prune_rate： 0.00 | qc_num: 5.34 | ac_num: 1.54 |
Finish loading dev data.
Loading sparse adj data...
| ori_adj_len: mu 12.02 sigma 9.17 | adj_len: 13.02 | prune_rate： 0.00 | qc_num: 5.48 | ac_num: 1.53 |
Finish loading test data.
Traceback (most recent call last):
  File "greaselm.py", line 606, in <module>
    main(args)
  File "greaselm.py", line 546, in main
    evaluate(args, has_test_split, devices, kg)
  File "greaselm.py", line 449, in evaluate
    dataset = load_data(args, devices, kg)
  File "greaselm.py", line 50, in load_data
    dataset = data_utils.GreaseLM_DataLoader(args.train_statements, args.train_adj,
  File "/data/xuanlong/Graph2Text/GreaseLM/utils/data_utils.py", line 144, in __init__
    with open(inhouse_train_qids_path, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'data/csqa/inhouse_split_qids.txt'
```

BR,

**Comment by YayangLi** [comment]
You can get it at "Learning Contextualized Knowledge Structures for Commonsense Reasoning", they following with "Knowledge-Aware Graph Networks for Commonsense Reasoning" by using random select on train data

**Comment by Spperman** [comment]
> Learning Contextualized Knowledge Structures for Commonsense Reasoning
Their specific download path is as follows：
wget -nc -P data/csqa/ https://raw.githubusercontent.com/INK-USC/MHGRN/master/data/csqa/inhouse_split_qids.txt

**Comment by Spperman** [comment]
> You can get it at "Learning Contextualized Knowledge Structures for Commonsense Reasoning", they following with "Knowledge-Aware Graph Networks for Commonsense Reasoning" by using random select on train data

Their specific download path is as follows：
wget -nc -P data/csqa/ https://raw.githubusercontent.com/INK-USC/MHGRN/master/data/csqa/inhouse_split_qids.txt

**Comment by weiyifan1023** [comment]
Their specific download path is as follows：
wget -nc -P data/csqa/ https://raw.githubusercontent.com/INK-USC/MHGRN/master/data/csqa/inhouse_split_qids.txt
